/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__test
#define __PYX_HAVE__test


#ifndef __PYX_HAVE_API__test

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) pythonAdd(int *);
__PYX_EXTERN_C DL_IMPORT(int) *numpyArray(int, int);

#endif /* !__PYX_HAVE_API__test */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inittest(void);
#else
PyMODINIT_FUNC PyInit_test(void);
#endif

#endif /* !__PYX_HAVE__test */
